import { useRef, useState, type KeyboardEvent } from "react";
import { cablesData, layoutData, partById, plannerData, referencesData, variantsData } from "../data";
import { layoutForVariant, movingMass, nodeWeight, preferredPartId } from "../lib/viewer";
import type { CustomRig, RigAdjustments, Variant } from "../lib/types";
import type { RigResolution } from "../lib/planner";
import type { ViewAngle } from "../components/RigViewer";
import PartsTable from "../components/PartsTable";
import PartInspector from "../components/PartInspector";
import ConnectionPanel, { SplitFeedDiagram, connectionName } from "../components/ConnectionPanel";
import AssemblyWizard from "../components/AssemblyWizard";
import RigSelection from "../components/RigSelection";
import Brand from "../components/Brand";
import brand from "../../data/brand.json";
import engineering from "../../data/engineering-manifest.json";
import ui from "../../data/ui-content.json";
import Icon from "../components/Icon";
import { partName } from "../lib/ui";
import { formatNumber } from "../lib/format";
import RigViewer from "../components/RigViewerLoader";
import AttachmentPicker from "../components/AttachmentPicker";
import PartAdjustments,{adjustablePart} from "../components/PartAdjustments";
interface Props {
 onAttach:(anchorId:string,optionId:string)=>void;
 onAdjust:(adjustments:RigAdjustments)=>void;
 profileName:string;onProfiles:()=>void;
 exploded:boolean;onExplodedChange:(v:boolean)=>void;onShowCablesChange:(v:boolean)=>void;onShowLabelsChange:(v:boolean)=>void;onVariantChange:(v:string)=>void;showCables:boolean;showLabels:boolean;variant:Variant;
 customRig:CustomRig|null;resolution:RigResolution|null;savedRigs:CustomRig[];dirty:boolean;message:string;recoveryStatus:string;viewerPaused:boolean;onHelp:()=>void;onDismissMessage:()=>void;onNewRig:()=>void;onLibrary:()=>void;onEditRig:()=>void;onSaveRig:()=>void;
}
const names:Record<string,string>={"documentary-one-man-film":"Documental / solo","commercial-solo-gimbal":"Comercial","handheld-quick-release":"A mano","lower-budget-stripped-down":"Esencial","vertical-916-creator-mode":"Vertical 9:16","corporate-interview":"Entrevista","cinema-narrative":"Cine / narrativa"};
const tabs=[{id:"design",label:"Rig",icon:"design"},{id:"connect",label:"Conexiones",icon:"connect"},{id:"assemble",label:"Montaje",icon:"assemble"},{id:"inventory",label:"Piezas",icon:"inventory"}] as const;
type Tab=typeof tabs[number]["id"];
export default function RigPlannerPage({profileName,onProfiles,exploded,onExplodedChange,onShowCablesChange,onShowLabelsChange,onVariantChange,showCables,showLabels,variant,customRig,resolution,savedRigs,dirty,message,recoveryStatus,viewerPaused,onHelp,onDismissMessage,onNewRig,onLibrary,onEditRig,onSaveRig,onAttach,onAdjust}:Props){
 const [tab,setTab]=useState<Tab>("design");const [selectedId,setSelectedId]=useState("");const [angle,setAngle]=useState<ViewAngle>("iso");const [bench,setBench]=useState(false);const [cableId,setCableId]=useState("");
 const [resetKey,setResetKey]=useState(0);
 const [attachmentAnchor,setAttachmentAnchor]=useState("");
 const [adjustmentPart,setAdjustmentPart]=useState("");
 const profileDialog=useRef<HTMLDialogElement>(null);
 const mass=movingMass(variant,layoutData,partById);
 const nodes=layoutForVariant(variant,layoutData).nodes.filter(n=>variant.active_part_ids.includes(n.id));
 const chosenIds=customRig?.part_ids??variant.active_part_ids;
 const attachmentRig:CustomRig=customRig??{schema_version:1,id:"rig-template-preview",name:variant.label,context:variant.viewer.rig_context??"handheld",orientation:variant.viewer.mode==="vertical"?"vertical":"landscape",part_ids:variant.active_part_ids,updated_at:"2026-10-07T00:00:00Z"};
 const focusPartId=chosenIds.includes(selectedId)?selectedId:preferredPartId(chosenIds,layoutData);
 const canAdjust=adjustablePart(focusPartId,variant);
 const adjust=()=>{onExplodedChange(false);setAdjustmentPart(focusPartId);requestAnimationFrame(()=>document.getElementById("workspace")?.scrollIntoView({block:"start"}));};
 const ids=bench?cablesData.profiles.requested_dual_feed_bench:variant.cable_profile_ids;
 const selectedCable=ids.includes(cableId)?cableId:ids[0]??"";
 const switchVariant=(id:string)=>{onVariantChange(id);setSelectedId("");setCableId("");setAdjustmentPart("");setAttachmentAnchor("");onExplodedChange(false);setBench(false);setResetKey(k=>k+1);};
 const switchTab=(id:Tab)=>{setTab(id);if(id==="connect"){onShowCablesChange(true);onShowLabelsChange(false);}if(id==="design"){setBench(false);onShowCablesChange(false);}if(window.matchMedia("(max-width:600px)").matches)requestAnimationFrame(()=>window.scrollTo({top:0,behavior:"auto"}));};
 const tabKey=(event:KeyboardEvent<HTMLButtonElement>,index:number)=>{if(!["ArrowLeft","ArrowRight","Home","End"].includes(event.key))return;event.preventDefault();const next=event.key==="Home"?0:event.key==="End"?3:(index+(event.key==="ArrowRight"?1:3))%4;switchTab(tabs[next].id);document.getElementById(`tab-${tabs[next].id}`)?.focus();};
 const inspect=(id:string)=>{setSelectedId(id);switchTab("design");requestAnimationFrame(()=>document.getElementById("workspace")?.scrollIntoView({block:"start"}));};
 const profileHints:Record<string,string>=ui.profile_hints;
 return <main className="app-shell">
  <header className="app-header"><Brand onHome={()=>{switchTab("design");requestAnimationFrame(()=>window.scrollTo({top:0,behavior:"auto"}));}}/><div className="header-actions"><button className="quiet-button local-profile-button" aria-label={`Perfil local: ${profileName}`} title={`Perfil local: ${profileName}`} onClick={onProfiles}><Icon name="person"/><span>{profileName}</span></button><button className="quiet-button" onClick={onLibrary}><Icon name="inventory"/>Mis rigs{savedRigs.length>0&&<span className="rig-count">{savedRigs.length}</span>}</button><button className="primary-button new-rig-button" aria-label="Crear rig" onClick={onNewRig}><Icon name="plus"/><span>Crear rig</span></button></div></header>
  {message&&<div role="status" className="app-message"><Icon name="info"/><p>{message}</p><button className="icon-button" aria-label="Cerrar aviso" onClick={onDismissMessage}><Icon name="close"/></button></div>}
  {recoveryStatus&&<p className="recovery-status" role="status">{recoveryStatus}</p>}
  <div className="project-bar"><div className="project-title"><p className="eyebrow">TU EQUIPO / {plannerData.camera_part_ids.some(id=>chosenIds.includes(id))?partName(preferredPartId(chosenIds,layoutData)):"MI SELECCIÓN"}</p><h1>{customRig?customRig.name||"Rig sin nombre":"Mi rig"}</h1><p className="profile-intent">{customRig?`${customRig.part_ids.length} elementos elegidos · ${dirty?"Borrador sin guardar":"Guardado en este navegador"}`:profileHints[variant.id]}</p></div><div className="build-controls"><label htmlFor="variant">Perfil</label><select id="variant" value={variant.id} onChange={e=>switchVariant(e.target.value)}><optgroup label="Plantillas">{variantsData.variants.map(v=><option value={v.id} key={v.id}>{names[v.id]}</option>)}</optgroup>{savedRigs.length>0&&<optgroup label="Mis rigs">{savedRigs.map(r=><option key={r.id} value={r.id}>{r.name||"Rig sin nombre"}</option>)}</optgroup>}</select><button className="profile-settings" aria-label="Detalles del perfil" onClick={()=>profileDialog.current?.showModal()}><Icon name="settings"/>Detalles del perfil</button></div></div>
  <div className="rig-action-bar"><span className={customRig?"custom-profile-tag":"template-profile-tag"}>{customRig?"PERFIL PROPIO":"PLANTILLA / COPIA EDITABLE"}</span><div><button className="quiet-button" onClick={onEditRig}><Icon name="settings"/>{customRig?"Editar piezas":"Personalizar"}</button><button className="primary-button" disabled={!!customRig&&!dirty} onClick={onSaveRig}><Icon name="check"/>{customRig&&!dirty?"Guardado":"Guardar rig"}</button></div></div>
  {resolution&&resolution.issues.length>0&&<details className="plan-pending"><summary><Icon name="info"/>{resolution.issues.length} {resolution.issues.length===1?"pendiente":"pendientes"} en este plan<span>Ver detalles</span></summary><ul>{resolution.issues.map(i=><li key={i.id}>{i.message}</li>)}</ul><button className="quiet-button" onClick={onEditRig}>Revisar selección</button></details>}
  <div className="navigation-row"><nav className="app-navigation" role="tablist" aria-label="Tareas del rig">{tabs.map((t,i)=><button key={t.id} role="tab" id={`tab-${t.id}`} aria-controls="task-panel" aria-selected={tab===t.id} tabIndex={tab===t.id?0:-1} onKeyDown={e=>tabKey(e,i)} onClick={()=>switchTab(t.id)}><Icon name={t.icon}/><span>{t.label}</span></button>)}</nav><button className="planning-state" onClick={()=>profileDialog.current?.showModal()}><i/>Revisión física pendiente<Icon name="info"/></button></div>
  <p className="task-hint">{ui.task_hints[tab]}</p>
  <section id="task-panel" role="tabpanel" aria-labelledby={`tab-${tab}`} className="task-panel">
  {(tab==="design"||tab==="connect")&&<div className="workspace" id="workspace">
    <div className="planner-toolbar"><div className="toolbar-primary"><div className="segmented">{tab==="connect"?<><button aria-pressed={!bench} onClick={()=>setBench(false)}>Mi rig</button><button aria-pressed={bench} onClick={()=>setBench(true)}>Doble HDMI <span>/ banco</span></button></>:<><button aria-pressed={!exploded} onClick={()=>onExplodedChange(false)}>Ensamble</button><button aria-pressed={exploded} onClick={()=>onExplodedChange(true)}>Despiece</button></>}</div>{tab==="design"&&<button className="connect-shortcut" aria-label="Ver conexiones" onClick={()=>switchTab("connect")}><Icon name="connect"/><span>Ver conexiones</span></button>}</div>
      {!bench&&<div className="view-tools"><select aria-label="Ángulo de vista" value={angle} onChange={e=>setAngle(e.target.value as ViewAngle)}><option value="iso">Vista 3/4</option><option value="side">Lateral</option><option value="front">Frontal</option></select><button className="icon-button" aria-label="Recentrar vista" title="Recentrar vista" onClick={()=>setResetKey(k=>k+1)}><Icon name="reset"/></button><details className="view-options"><summary aria-label="Opciones del visor"><Icon name="settings"/></summary><div className="view-options-menu"><label className="inline-check"><input type="checkbox" checked={showLabels} onChange={e=>onShowLabelsChange(e.target.checked)}/>Etiquetas</label><label className="inline-check"><input type="checkbox" checked={showCables} onChange={e=>onShowCablesChange(e.target.checked)}/>{tab==="connect"?"Todos los cables":"Cableado"}</label><button className="mobile-reset" onClick={()=>setResetKey(k=>k+1)}><Icon name="reset"/>Recentrar vista</button></div></details></div>}
    </div>
    {tab==="connect"&&<label className="mobile-connection-picker">Conexión<select aria-label="Conexión" value={selectedCable} onChange={e=>setCableId(e.target.value)}>{ids.map(id=><option key={id} value={id}>{connectionName(id)}</option>)}</select></label>}
    <div className="workspace-body"><div className="viewer-column">{tab==="connect"&&bench?<SplitFeedDiagram selectedId={selectedCable} onSelect={setCableId}/>:viewerPaused?<div className="viewer-fallback">Vista en pausa mientras configuras el plan.</div>:nodes.length===0?<div className="rig-empty-canvas"><span><Icon name="design"/></span><h2>Tu rig empieza aquí</h2><p>Elige la cámara, la óptica y los accesorios. El visor mostrará sólo las piezas con una cadena de montaje documentada.</p><button className="primary-button" onClick={onEditRig}><Icon name="plus"/>Elegir mis piezas</button></div>:<RigViewer variant={variant} exploded={exploded} showLabels={showLabels} showCables={showCables} selectedId={nodes.some(n=>n.id===focusPartId)?focusPartId:""} onSelect={setSelectedId} angle={angle} selectedCableId={tab==="connect"?selectedCable:null} resetKey={resetKey}/>}
      {tab==="design"&&<div className="part-strip" aria-label="Piezas del rig">{chosenIds.map(id=><button key={id} className={resolution?.parked_ids.includes(id)?"is-pending":""} aria-pressed={focusPartId===id} onClick={()=>setSelectedId(id)}>{partName(id)}{resolution?.parked_ids.includes(id)?" · pendiente":""}</button>)}</div>}
      {tab==="design"&&focusPartId&&<div className="mobile-part-focus"><span>{partName(focusPartId)}</span><button onClick={()=>setAttachmentAnchor(focusPartId)}><Icon name="plus"/>Añadir accesorio</button>{canAdjust&&<button onClick={adjust}><Icon name="settings"/>Ajustar</button>}<button onClick={()=>document.getElementById("part-inspector")?.scrollIntoView({block:"start"})}>Ver ficha<Icon name="arrow"/></button></div>}
      {bench?<div className="bench-context"><Icon name="info"/><p><strong>Circuito de referencia, independiente del perfil.</strong> Requiere las piezas y fuentes indicadas. No añade un soporte de distribuidor HDMI al rig ni modifica tu configuración.</p></div>:nodes.length>0?<div className="workspace-summary"><div><span>CARGA MÓVIL ESTIMADA</span><strong>~ {formatNumber(mass.subtotal/1000,2)} <small>kg</small></strong></div><p>Subtotal incompleto: faltan cables, fijaciones{!(plannerData.camera_external_power_part_ids??[]).some(id=>variant.active_part_ids.includes(id))?" y batería interna de cámara":""}{mass.unknown?"; masas pendientes":""}. {nodes.some(n=>n.kind==="monitor")?(nodes.find(n=>n.kind==="monitor")?.mass_domain==="fixed"?"Monitor lateral fuera de la carga móvil.":"Monitor y batería elegida incluidos en el núcleo."):"Sin monitor externo activo."}</p><button onClick={()=>profileDialog.current?.showModal()}>Desglose<Icon name="arrow"/></button></div>:null}
    </div>{tab==="connect"?<ConnectionPanel variant={variant} bench={bench} selectedId={selectedCable} onSelect={setCableId}/>:focusPartId&&partById[focusPartId]?<PartInspector selectedId={focusPartId} variant={variant} onAttach={()=>setAttachmentAnchor(focusPartId)} onAdjust={canAdjust?adjust:undefined}/>:<aside className="empty-inspector"><Icon name="inventory"/><h3>Construye tu lista de equipo</h3><p>Las piezas en reserva siguen en tu perfil, con sus pendientes visibles. No aparecen como instaladas en el visor.</p></aside>}</div>
    {tab==="design"&&customRig&&resolution&&chosenIds.length>0&&<RigSelection chosenIds={chosenIds} variant={variant} resolution={resolution} selectedId={focusPartId} onSelect={setSelectedId} onEdit={onEditRig}/>}
    <div className="workspace-notice"><Icon name="info"/><p>{bench?"Diagrama lógico. Comprueba señal, alimentación y conectores antes de encender.":"Modelo aproximado. Comprueba motores, manos y bucles antes de encender."}</p><button onClick={()=>profileDialog.current?.showModal()}>Ver comprobaciones</button></div>
  </div>}
  <div hidden={tab!=="assemble"}><AssemblyWizard variant={variant} chosenIds={chosenIds} active={tab==="assemble"&&!viewerPaused} onEdit={onEditRig}/></div>
  {tab==="inventory"&&<div className="inventory-workspace"><div className="panel-heading"><h2>Equipo del proyecto</h2><p>{chosenIds.length} {chosenIds.length===1?"elemento elegido":"elementos elegidos"}</p></div><PartsTable key={variant.id} variant={variant} chosenIds={chosenIds} selectedId={selectedId} onSelect={inspect} onEdit={onEditRig}/></div>}
  </section>
  <footer className="app-footer"><span>{brand.name.toUpperCase()} / PLANIFICACIÓN DE RODAJE</span><p>Fuentes verificadas. Geometría aproximada, no CAD certificado.</p><button className="quiet-button" onClick={onHelp}>Ayuda y versión</button></footer>
  {attachmentAnchor&&<AttachmentPicker key={`${variant.id}:${attachmentAnchor}`} anchorId={attachmentAnchor} rig={attachmentRig} onClose={()=>setAttachmentAnchor("")} onAdd={optionId=>{onAttach(attachmentAnchor,optionId);setAttachmentAnchor("");}} onCatalog={()=>{setAttachmentAnchor("");onEditRig();}}/>}
  {adjustmentPart&&adjustablePart(adjustmentPart,variant)&&<PartAdjustments key={adjustmentPart} partId={adjustmentPart} variant={variant} onChange={onAdjust} onClose={()=>setAdjustmentPart("")}/>}
  <dialog ref={profileDialog} className="profile-dialog" aria-labelledby="profile-title"><div className="dialog-heading"><div><p className="eyebrow">TU PERFIL / CRITERIOS DE MONTAJE</p><h2 id="profile-title">{names[variant.id]??variant.label}</h2></div><button className="icon-button" aria-label="Cerrar detalles del perfil" onClick={()=>profileDialog.current?.close()}><Icon name="close"/></button></div>
   <div className="dialog-content"><p className="dialog-intro">{variant.workflow_impact}</p><div className="profile-pills">{variantsData.variants.map(v=><button key={v.id} aria-pressed={v.id===variant.id} onClick={()=>switchVariant(v.id)}>{names[v.id]}</button>)}</div>
   <h3>Carga móvil modelada</h3><div className="mass-breakdown">{nodes.filter(n=>n.mass_domain==="moving").map(n=>{const weight=nodeWeight(n,partById[n.id]);return <div key={n.id}><span>{n.label}{!weight.published?" / estimado":""}</span><b>{weight.value===null?"?":(weight.approximate?"~ ":"")+formatNumber(weight.value!)} g</b></div>})}</div><p className="panel-footnote">Suma de masas de planificación, incluye estimaciones. Incluye sólo los 28 g del RX Mic 2 cuando está activo, nunca TX ni estuche. No incluye cables, tarjetas ni tornillería adicional. BG70 sustituye a BG30. Centro de gravedad real no medido.</p>
   <details><summary>Distribución y límites publicados</summary><p><b>Centro ponderado de envolventes:</b> {mass.envelopeCentroid?.map(v=>Math.round(v)).join(" / ")} mm (X / Y / Z, origen cuerpo FX3). Es una aproximación de la distribución, no el centro de gravedad real ni un ajuste de equilibrio.</p><p><b>RS 4 Pro:</b> {formatNumber(engineering.limits.rs4_pro_tested_payload_g/1000)} kg nominales. No certifica holguras, inercia ni rig completo.</p><p><b>3026B:</b> carga publicada {formatNumber(engineering.limits["3026b_supported_load_g"]/1000)} kg. Indie 7: 737 g sin cables; carga estática nominal no demuestra rigidez ni seguridad dinámica.</p><p><b>Bloque trasero:</b> VB99 Pro 644 g + 3203B 351 g conservadores = 995 g bajo varillas; exige barrido de giro/inclinación. La carga admisible de esa pila no se ha verificado.</p><a href={engineering.limits["3026b_source_url"]} target="_blank" rel="noreferrer">Manual de soporte y límite de carga</a></details>
   <details><summary>Qué cambia en este perfil</summary><p><b>Equilibrio:</b> {variant.balance_impact}</p><p><b>Presupuesto:</b> {variant.budget_impact}</p><p><b>Complejidad:</b> {variant.complexity_impact}</p><p><b>Retirados:</b> {variant.parts_removed.map(partName).join(", ")||"Ninguno"}</p><p><b>Añadidos:</b> {variant.parts_added.map(partName).join(", ")||"Ninguno"}</p><p><b>Dependencias:</b> {variant.dependencies.join("; ")}</p></details>
   {variant.conditional_part_ids.length>0&&<details><summary>Accesorios en reserva</summary><p>{variant.conditional_part_ids.map(partName).join("; ")}</p></details>}
   <h3>Pruebas antes de producción</h3>{layoutData.clearance_gates.map(g=><details key={g.id}><summary>{g.title} <span>Pendiente</span></summary><p>{g.detail}</p></details>)}
   <details><summary>Cambios de conexiones frente a Comercial</summary><p><b>Retiradas:</b> {variant.cables_removed.map(connectionName).join("; ")||"Ninguna"}</p><p><b>Añadidas:</b> {variant.cables_added.map(connectionName).join("; ")||"Ninguna"}</p></details>
   <details><summary>Alternativa de menor presupuesto</summary><p>Perfil Esencial: sin monitor externo, V-mount, varillas ni parasol. Pantalla FX3 e interna NP-FZ100 confirmada. Monitor & Control es opcional con dispositivo/firmware compatibles; no se inventa soporte de teléfono.</p><button className="quiet-button" onClick={()=>switchVariant("lower-budget-stripped-down")}>Usar Esencial →</button></details>
   <details><summary>Referencias, CAD y licencias</summary><p>{referencesData.license_note}</p><p>Se encontró un escaneo comunitario de FX3, pero su descarga, escala y licencia no quedaron verificadas. No se importa como CAD mecánico.</p><a href="https://sketchfab.com/3d-models/sony-fx3-camera-scan-8eaae19fabce47daa5c0d031a1f0fc5e" target="_blank" rel="noreferrer">Consultar candidato comunitario</a></details>
   </div>
  </dialog>
 </main>;
}
