import { useEffect, useRef, useState } from "react";
import release from "../../data/release.json";
import { prepareOffline } from "../lib/offline";
import Icon from "./Icon";
import PilotModels from "./PilotModels";

export default function HelpCenter({onClose,onNew,onLibrary}:{onClose:()=>void;onNew:()=>void;onLibrary:()=>void}){
  const dialog=useRef<HTMLDialogElement>(null);
  const [offline,setOffline]=useState(""),[busy,setBusy]=useState(false),[description,setDescription]=useState(""),[report,setReport]=useState("");
  useEffect(()=>{dialog.current?.showModal();},[]);
  const enableOffline=async()=>{setBusy(true);setOffline("Descargando recursos propios…");try{setOffline(await prepareOffline());}catch(error){setOffline(error instanceof Error?error.message:"No se confirmó la preparación sin conexión.");}finally{setBusy(false);}};
  const copyReport=async()=>{try{await navigator.clipboard.writeText(`Takegrid ${release.version}\nQué ocurrió y cómo reproducirlo:\n${description.trim()}\n\nNo incluye biblioteca, nombres de rigs ni telemetría automática.`);setReport("Descripción copiada. No se envió automáticamente a ningún servicio.");}catch{setReport("No se pudo copiar. Tu descripción sigue aquí.");}};
  return <dialog ref={dialog} className="profile-dialog help-dialog" aria-labelledby="help-title" onCancel={onClose} onClose={onClose}>
    <div className="dialog-heading"><div><p className="eyebrow">TAKEGRID {release.version} / {release.label.toUpperCase()}</p><h2 id="help-title">Prepara tu rig</h2></div><button className="icon-button" aria-label="Cerrar ayuda" onClick={onClose}><Icon name="close"/></button></div>
    <div className="dialog-content"><ol className="help-steps"><li><strong>Elige tu equipo.</strong> Crea desde cero o personaliza una plantilla. Una pieza elegida puede quedar pendiente si falta soporte.</li><li><strong>Revisa conexiones y montaje.</strong> Consulta los extremos A/B, reproduce sólo las etapas pertinentes y comprueba el rig físico antes de encender.</li><li><strong>Guarda para el rodaje.</strong> Mis rigs conserva los planes confirmados y su historial en este navegador.</li></ol><div className="help-actions"><button className="primary-button" onClick={()=>{onClose();onNew();}}>Crear mi rig</button><button className="quiet-button" onClick={()=>{onClose();onLibrary();}}>Abrir Mis rigs</button></div>
      <details><summary>Recuperación y cambios de otra pestaña</summary><p>Los borradores se preparan automáticamente para recuperación local. Sólo el aviso de recuperación confirma esa copia; Guardar rig confirma el plan. En Mis rigs puedes recuperar un borrador o una versión anterior como copia, sin reemplazar el original.</p><p>Si otra pestaña cambió la biblioteca, usa Revisar cambios de otra pestaña. Los cambios de esta sesión quedan como copias editables. No es colaboración ni sincronización entre dispositivos.</p></details>
      <details><summary>Preparar uso sin conexión</summary><p>Descarga únicamente código, datos y recursos propios. Los planes siguen locales; no se guardan en un servidor. Las páginas de fabricantes y fuentes tipográficas externas necesitan red. No se recargan pestañas ni se activa una versión nueva sobre tus borradores.</p><button className="quiet-button" disabled={busy||!__PUBLIC_DEMO__} onClick={enableOffline}>Preparar recursos sin conexión</button><p role="status">{offline}</p><p>Para instalar, usa la opción del navegador de añadir o instalar la web, si está disponible. Esta versión no está publicada en App Store.</p></details>
      <details><summary>Describir un problema</summary><label className="report-label">Qué esperabas, qué pasó y pasos para reproducirlo<textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={2000} placeholder="No incluyas datos de clientes ni información confidencial."/></label><button className="quiet-button" disabled={!description.trim()} onClick={copyReport}>Copiar descripción</button><p role="status">{report}</p><p>Este formulario no envía informes ni exporta tu plan. Comparte la descripción por el canal acordado con el equipo; todavía no hay un servicio de soporte conectado.</p></details>
      <details><summary>Datos y privacidad</summary><p>Biblioteca, historial y borradores viven en el almacenamiento de este navegador y dominio. Eliminar un rig confirmado elimina su historial; los borradores de otras sesiones se descartan por separado. Borrar datos del sitio, usar una sesión privada o perder el equipo puede eliminar todo: no existe copia externa.</p><p>El laboratorio no envía telemetría. El alojamiento recibe las solicitudes web habituales; las fuentes tipográficas se solicitan a Google y los enlaces oficiales abren al fabricante. No se declara auditoría legal de privacidad.</p></details>
      <details><summary>Alcance de esta versión</summary><ul>{release.limitations.map(item=><li key={item}>{item}</li>)}</ul><a className="quiet-button" href="/?laboratorio=1">Abrir laboratorio de rendimiento</a></details>
      <details><summary>Modelos del piloto en revisión</summary><PilotModels /></details>
    </div>
  </dialog>;
}
