import { useDeferredValue, useEffect, useRef, useState } from "react";
import { layoutData, partById, plannerData } from "../data";
import { dependencyClosure, type RigResolution } from "../lib/planner";
import type { CustomRig } from "../lib/types";
import { partName } from "../lib/ui";
import Icon from "./Icon";

export default function RigBuilder({open,onClose,rig,resolution,onChange,onSave,dirty,message}:{open:boolean;onClose:()=>void;rig:CustomRig;resolution:RigResolution;onChange:(r:CustomRig)=>void;onSave:()=>void;dirty:boolean;message:string}){
 const dialog=useRef<HTMLDialogElement>(null);
 const [category,setCategory]=useState("core");const [query,setQuery]=useState("");
 const q=useDeferredValue(query.trim().toLocaleLowerCase("es"));
 useEffect(()=>{if(open&&!dialog.current?.open)dialog.current?.showModal();if(!open&&dialog.current?.open)dialog.current.close();},[open]);
 const toggle=(id:string)=>onChange({...rig,part_ids:rig.part_ids.includes(id)?rig.part_ids.filter(p=>p!==id):[...rig.part_ids,id]});
 const categoryIds=plannerData.categories.find(c=>c.id===category)!.part_ids;
 const ids=(q?plannerData.categories.flatMap(c=>c.part_ids):categoryIds).filter(id=>`${partName(id)} ${partById[id].exact_product_name} ${partById[id].model_number??""}`.toLocaleLowerCase("es").includes(q));
 const missing=[...new Set(resolution.issues.flatMap(i=>i.add_ids))];
 return <dialog ref={dialog} className="builder-dialog" aria-labelledby="builder-title" onCancel={onClose} onClose={onClose}>
  <div className="dialog-heading"><div><p className="eyebrow">TU EQUIPO, TU PLAN</p><h2 id="builder-title">Configurar rig</h2></div><button className="icon-button" aria-label="Cerrar editor de rig" onClick={onClose}><Icon name="close"/></button></div>
  <div className="builder-settings"><label>Nombre del rig<input aria-label="Nombre del rig" value={rig.name} maxLength={80} onChange={e=>onChange({...rig,name:e.target.value})}/></label><label>Tipo de uso<select aria-label="Tipo de uso" value={rig.context} onChange={e=>onChange({...rig,context:e.target.value as CustomRig["context"]})}><option value="gimbal">Gimbal</option><option value="handheld">A mano</option><option value="static">Cámara estática</option></select></label><label>Encuadre<select aria-label="Encuadre" value={rig.orientation} onChange={e=>onChange({...rig,orientation:e.target.value as CustomRig["orientation"]})}><option value="landscape">Horizontal</option><option value="vertical">Vertical 9:16</option></select></label></div>
  <div className="builder-body"><section className="builder-catalog" aria-label="Elegir piezas"><label className="search-field"><Icon name="search"/><input aria-label="Buscar en el catálogo" placeholder="Busca cámara, modelo, accesorio..." value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="catalog-categories" aria-label="Categorías del catálogo">{plannerData.categories.map(c=><button key={c.id} aria-pressed={category===c.id&&!q} onClick={()=>{setCategory(c.id);setQuery("");}}>{c.label}</button>)}</div><div className="builder-items">{ids.map(id=>{
   const part=partById[id];const chosen=rig.part_ids.includes(id);const parked=resolution.parked_ids.includes(id);const modeled=layoutData.nodes.some(n=>n.id===id);
   return <label key={id} className={`build-item ${chosen?"is-chosen":""} ${parked?"is-pending":""}`}><input type="checkbox" aria-label={`Elegir ${partName(id)}`} checked={chosen} onChange={()=>toggle(id)}/><span className="build-item-icon"><Icon name={category==="power"?"connect":category==="core"?"design":"inventory"}/></span><span><small>{part.brand} / {part.model_number??"Catálogo verificado"}</small><strong>{partName(id)}</strong><small>{part.planning_weight_g===null?"Masa pendiente":`~ ${part.planning_weight_g} g de planificación`}{!modeled?" · Sin geometría de montaje":""}</small></span><span className="item-selection-state">{parked?"Pendiente":chosen?"Elegido":"Añadir"}</span></label>;
  })}</div>{ids.length===0&&<p className="empty-state">No hay coincidencias en este catálogo.</p>}<p className="panel-footnote">Catálogo actual: 25 productos y 2 componentes del Combo. Sin piezas ni montajes inventados.</p></section>
  <aside className="builder-review"><div className="builder-counter"><Icon name="design"/><strong>{rig.part_ids.length}<small>elementos elegidos</small></strong></div><p>{resolution.variant.active_part_ids.length} en plan · {resolution.parked_ids.length} en reserva</p><h3>Para completar tu plan</h3>{resolution.issues.length===0?<p>Selección coherente con las reglas actuales. Quedan las pruebas físicas antes de rodaje.</p>:<ul className="builder-issues">{resolution.issues.map(i=><li key={i.id}><Icon name="info"/><span>{i.message}</span></li>)}</ul>}{missing.length>0&&<button className="quiet-button" onClick={()=>onChange({...rig,part_ids:dependencyClosure([...rig.part_ids,...missing],plannerData)})}>Añadir dependencias disponibles</button>}<details><summary>Qué comprueba Takegrid</summary><p>Cadenas de soporte documentadas, contexto de uso y extremos de conexiones. No prueba torque, holguras, capacidad dinámica, polaridad ni estabilidad. Puedes guardar planes incompletos: sus pendientes siguen visibles.</p></details></aside></div>
  <div className="builder-actions">{message&&<p className="builder-feedback" role="status">{message}</p>}<span>{dirty?"Borrador sin guardar":"Guardado en este navegador"}</span><button className="quiet-button" onClick={onClose}>Ver mi rig</button><button className="primary-button" onClick={onSave} disabled={!rig.name.trim()}><Icon name="check"/>Guardar rig</button></div>
 </dialog>;
}
