import { useEffect, useRef, useState } from "react";
import { variantsData } from "../data";
import type { CustomRig, Variant } from "../lib/types";
import Icon from "./Icon";
import type { RecoverableDraft } from "../lib/drafts";

interface Props {open:boolean;onClose:()=>void;rigs:CustomRig[];saved:CustomRig[];history:Record<string,CustomRig[]>;recoverable:RecoverableDraft[];onRecover:(draft:RecoverableDraft)=>void;onDiscard:(draft:RecoverableDraft)=>void;onRefresh:()=>void;onOpen:(id:string)=>void;onCreate:()=>void;onTemplate:(v:Variant)=>void;onDuplicate:(r:CustomRig)=>void;onDelete:(id:string)=>void}
export default function RigLibrary({open,onClose,rigs,saved,history,recoverable,onRecover,onDiscard,onRefresh,onOpen,onCreate,onTemplate,onDuplicate,onDelete}:Props){
 const dialog=useRef<HTMLDialogElement>(null);const [deleteId,setDeleteId]=useState<string|null>(null);
 useEffect(()=>{if(open&&!dialog.current?.open)dialog.current?.showModal();if(!open&&dialog.current?.open)dialog.current.close();},[open]);
 return <dialog ref={dialog} className="library-dialog" aria-labelledby="library-title" onCancel={onClose} onClose={onClose}>
  <div className="dialog-heading"><div><p className="eyebrow">PREPARA TU PRÓXIMO RODAJE</p><h2 id="library-title">Mis rigs</h2></div><button className="icon-button" aria-label="Cerrar biblioteca" onClick={onClose}><Icon name="close"/></button></div>
  <div className="library-content"><div className="library-tools"><button className="primary-button" onClick={onCreate}><Icon name="plus"/>Crear rig desde cero</button><button className="quiet-button" onClick={onRefresh}>Revisar cambios de otra pestaña</button></div><p className="library-note">Guardado local, sin cuenta ni sincronización. Guardar confirma el plan y conserva hasta cinco versiones. Los borradores tienen recuperación automática si el navegador permite almacenamiento; no sustituye una copia de seguridad fuera de este equipo.</p>
  {recoverable.length>0&&<details className="recovery-list"><summary>{recoverable.length} borradores recuperables</summary><p>Se abren como copias. No reemplazan un rig guardado.</p>{recoverable.map(d=><article key={d.key}><strong>{d.rig.name||"Sin nombre"}</strong><p>{d.rig.part_ids.length} elementos · {new Date(d.recorded_at).toLocaleString("es")}</p><button className="quiet-button" onClick={()=>onRecover(d)}>Recuperar como copia</button><button className="quiet-button" onClick={()=>setDeleteId(d.key)}>Descartar</button>{deleteId===d.key&&<div className="delete-rig-confirm"><p>¿Descartar este borrador local? No afecta al plan confirmado.</p><button onClick={()=>{onDiscard(d);setDeleteId(null);}}>Sí, descartar borrador</button><button onClick={()=>setDeleteId(null)}>Cancelar</button></div>}</article>)}</details>}
  {rigs.length===0?<div className="library-empty"><Icon name="design"/><h3>Un rig para cada rodaje</h3><p>Elige cada pieza desde cero o usa una plantilla como punto de partida.</p></div>:<div className="rig-card-grid">{rigs.map(r=>{
   const dirty=JSON.stringify(r)!==JSON.stringify(saved.find(s=>s.id===r.id));
   return <article className="saved-rig-card" key={r.id}><span className="saved-rig-symbol"><Icon name="design"/></span><span className={dirty?"draft-badge":"saved-badge"}>{dirty?"Borrador":"Guardado"}</span><h3>{r.name||"Sin nombre"}</h3><p>{r.part_ids.length} elementos · {r.context==="gimbal"?"Gimbal":r.context==="handheld"?"A mano":"Estático"} · {r.orientation==="vertical"?"9:16":"Horizontal"}</p><button className="rig-open" onClick={()=>onOpen(r.id)}>Abrir rig<Icon name="arrow"/></button><div className="rig-card-actions"><button onClick={()=>onDuplicate(r)}>Duplicar</button><button onClick={()=>setDeleteId(r.id)}>Eliminar</button></div>{(history[r.id]?.length??0)>1&&<details className="rig-history"><summary>Historial local</summary>{history[r.id].slice(0,-1).reverse().map((snapshot,index)=><button key={index} onClick={()=>onDuplicate(snapshot)}>{new Date(snapshot.updated_at).toLocaleString("es")} · {snapshot.part_ids.length} elementos · Abrir como copia</button>)}</details>}{deleteId===r.id&&<div className="delete-rig-confirm"><p>¿Eliminar este rig y su historial de la biblioteca local?</p><button onClick={()=>{onDelete(r.id);setDeleteId(null);}}>Sí, eliminar</button><button onClick={()=>setDeleteId(null)}>Cancelar</button></div>}</article>;
  })}</div>}
  <h3 className="library-section-title">Partir de una plantilla</h3><div className="template-grid">{variantsData.variants.map(v=><button key={v.id} onClick={()=>onTemplate(v)}><Icon name={v.id==="handheld-quick-release"?"design":"assemble"}/><span><strong>{v.label}</strong><small>{v.active_part_ids.length} elementos · Copia editable</small></span><Icon name="arrow"/></button>)}</div></div>
 </dialog>;
}
