import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import ts from "typescript";

const read=name=>JSON.parse(readFileSync(new URL(`../data/${name}.json`,import.meta.url),"utf8"));
const rules=read("planner-rules"),parts=read("parts-manifest").parts,cables=read("cables-manifest").cables;
const variants=read("variants").variants,master=variants.find(v=>v.id==="commercial-solo-gimbal");
const catalog=parts.map(p=>p.id);
const compiled=ts.transpileModule(readFileSync(new URL("../src/lib/planner.ts",import.meta.url),"utf8"),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;
const {resolveRig,dependencyClosure,assemblyFrame,parseRig,parseLibrary,newRig,writeLibrary,LIBRARY_KEY}=await import(`data:text/javascript;base64,${Buffer.from(compiled).toString("base64")}`);
const rig=(ids=[],context="gimbal",orientation="landscape")=>({schema_version:1,id:"rig-qa",name:"Plan de prueba",context,orientation,part_ids:ids,updated_at:"2026-10-05T00:00:00.000Z"});
const resolve=r=>resolveRig(r,rules,cables,master,id=>id);
let checks=0;
function test(name,run){run();checks++;console.log(`CORRECTO: ${name}`);}

test("Un rig vacío no añade piezas ni cables",()=>{const r=resolve(rig());assert.equal(r.variant.active_part_ids.length,0);assert.equal(r.variant.cable_profile_ids.length,0);assert(r.issues.length>0);});
test("Las dependencias no modifican elecciones del usuario",()=>{const input=rig(["smallrig-vb99-pro"]),snapshot=JSON.stringify(input);const r=resolve(input);assert.deepEqual(r.parked_ids,["smallrig-vb99-pro"]);assert.equal(JSON.stringify(input),snapshot);assert.equal(r.variant.active_part_ids.length,0);});
test("La cadena V-mount baja requiere varillas, base y jaula",()=>{const ids=dependencyClosure(["smallrig-vb99-pro"],rules);for(const id of ["smallrig-3203b","smallrig-rods-8in","smallrig-1674","smallrig-4770","sony-fx3"])assert(ids.includes(id));assert(resolve(rig(ids)).variant.active_part_ids.includes("smallrig-vb99-pro"));});
test("Una copia de Comercial conserva sus circuitos",()=>{const r=resolve(rig(master.active_part_ids));assert.deepEqual(new Set(r.variant.active_part_ids),new Set(master.active_part_ids));assert.deepEqual(new Set(r.variant.cable_profile_ids),new Set(master.cable_profile_ids));});
test("Quitar un soporte retira la geometría y los cables dependientes",()=>{const r=resolve(rig(master.active_part_ids.filter(id=>id!=="smallrig-rods-8in")));for(const id of ["smallrig-3203b","smallrig-vb99-pro","smallrig-4253b"])assert(!r.variant.active_part_ids.includes(id));assert(!r.variant.cable_profile_ids.includes("pwr-vmount-to-fx3-dummy"));});
test("Accesorios sin soporte no se activan",()=>{const r=resolve(rig(catalog));for(const id of rules.parked_part_ids)assert(r.parked_ids.includes(id));assert(r.parked_ids.includes("sony-xlr-h1"));assert(!r.variant.cable_profile_ids.some(id=>cables.find(c=>c.cable_id===id).status!=="candidate"));});
test("El monitor estático no recibe un soporte inventado",()=>{const r=resolve(rig(catalog,"static"));assert(!r.variant.active_part_ids.includes("smallhd-indie-7"));assert(r.issues.some(i=>i.id==="static-support"));});
test("Vertical retira la pila no documentada",()=>{const r=resolve(rig(master.active_part_ids,"gimbal","vertical"));assert.equal(r.variant.viewer.mode,"vertical");for(const id of rules.vertical_excluded_part_ids)assert(!r.variant.active_part_ids.includes(id));});
test("Audio con asa no duplica la conexión al cuerpo",()=>{const r=resolve(rig(["sony-fx3","sony-fe-16-35-gm","smallrig-4770","sony-xlr-h1","dji-mic-2-kit","dji-lavalier"],"handheld"));assert(r.variant.cable_profile_ids.includes("audio-rx-to-xlrhandle"));assert(!r.variant.cable_profile_ids.includes("audio-rx-to-fx3"));});
test("El cable de vídeo es un elemento elegido, no implícito",()=>{const r=resolve(rig(master.active_part_ids.filter(id=>id!=="kondor-blue-hdmi-aa")));assert(!r.variant.cable_profile_ids.includes("vid-fx3-to-smallhd"));assert(r.issues.some(i=>i.id==="monitor-video"));});
test("Etapas acumulativas y extracción sin añadir equipo",()=>{let previous=[];for(let step=1;step<=12;step++){const f=assemblyFrame(master,step,rules,cables);for(const id of previous)assert(f.variant.active_part_ids.includes(id));previous=f.variant.active_part_ids.filter(id=>!f.context_ids.includes(id));for(const id of f.variant.active_part_ids)assert(master.active_part_ids.includes(id));}const extraction=assemblyFrame(master,13,rules,cables);assert(!extraction.variant.active_part_ids.includes("dji-rs4-pro-combo"));assert(!extraction.variant.active_part_ids.includes("sony-xlr-h1"));assert.equal(extraction.variant.cable_profile_ids.length,0);});
test("Los cables aparecen sólo a partir de su etapa",()=>{const at8=assemblyFrame(master,8,rules,cables),at9=assemblyFrame(master,9,rules,cables),at11=assemblyFrame(master,11,rules,cables);assert(!at8.variant.cable_profile_ids.includes("vid-fx3-to-smallhd"));assert(at9.variant.cable_profile_ids.includes("vid-fx3-to-smallhd"));assert(!at9.variant.cable_profile_ids.includes("pwr-vmount-to-fx3-dummy"));assert(at11.variant.cable_profile_ids.includes("pwr-vmount-to-fx3-dummy"));});
test("Guardar y recargar un documento conserva sus elecciones",()=>{const r=rig(master.active_part_ids),library={version:1,rigs:[r]};assert.deepEqual(parseLibrary(JSON.stringify(library),catalog,40),library);assert.deepEqual(parseRig(r,catalog),r);});
test("Importaciones inválidas y bibliotecas duplicadas se rechazan",()=>{for(const value of [null,{},rig(["cámara-inventada"]),rig(["sony-fx3","sony-fx3"]),{...rig(),schema_version:2},{...rig(),name:""},{...rig(),context:"trípode-inventado"},{...rig(),updated_at:"incorrecto"}])assert.throws(()=>parseRig(value,catalog));assert.throws(()=>parseLibrary("{",catalog,40));assert.throws(()=>parseLibrary(JSON.stringify({version:1,rigs:[rig(),rig()]}),catalog,40));assert.throws(()=>parseLibrary(JSON.stringify({version:1,rigs:[rig()]}),catalog,0));});
test("Nuevos perfiles usan identificadores propios y no mutan plantillas",()=>{const before=JSON.stringify(master),a=newRig("Copia",master),b=newRig();assert.notEqual(a.id,b.id);a.part_ids.pop();assert.equal(JSON.stringify(master),before);assert.equal(b.part_ids.length,0);parseRig(a,catalog);});
test("300 selecciones conservan cadenas, extremos y una sola HDMI",()=>{let seed=19;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/2**32;};for(let i=0;i<300;i++){const selected=catalog.filter(()=>random()>.4),r=resolve(rig(selected,["gimbal","handheld","static"][i%3],i%2?"vertical":"landscape"));const active=new Set(r.variant.active_part_ids);for(const id of active){assert(selected.includes(id));for(const dep of rules.mount_dependencies[id]??[])assert(active.has(dep));}for(const id of r.variant.cable_profile_ids){const c=cables.find(c=>c.cable_id===id);assert.equal(c.status,"candidate");assert(active.has(c.source_part_id));for(const endpoint of [c.from_part_id,c.to_part_id])assert(endpoint===null||active.has(endpoint));}assert(!r.variant.cable_profile_ids.includes("vid-fx3-to-startech-splitter"));}});
const memory=()=>{const data=new Map();return {data,getItem:key=>data.get(key)??null,setItem:(key,value)=>data.set(key,value)};};
test("La escritura confirma una biblioteca recuperable",()=>{const store=memory(),serialized=writeLibrary(store,null,[rig()],catalog,40);assert.equal(store.getItem(LIBRARY_KEY),serialized);assert.deepEqual(parseLibrary(serialized,catalog,40).rigs,[rig()]);});
test("Una escritura obsoleta no pisa otra pestaña",()=>{const store=memory(),latest=writeLibrary(store,null,[rig()],catalog,40);assert.throws(()=>writeLibrary(store,null,[{...rig(),name:"Borrador obsoleto"}],catalog,40),/otra pestaña/);assert.equal(store.getItem(LIBRARY_KEY),latest);});
test("Errores de cuota o permisos no confirman guardado",()=>{const blocked={getItem:()=>null,setItem:()=>{throw new Error("Cuota de prueba");}};assert.throws(()=>writeLibrary(blocked,null,[rig()],catalog,40));});
test("Bibliotecas ilegibles se respaldan antes de reemplazarse",()=>{const store=memory();store.setItem(LIBRARY_KEY,"{archivo ilegible");writeLibrary(store,"{archivo ilegible",[rig()],catalog,40);assert.equal(store.getItem(`${LIBRARY_KEY}.backup`),"{archivo ilegible");assert.equal(parseLibrary(store.getItem(LIBRARY_KEY),catalog,40).rigs.length,1);});
test("El límite de biblioteca falla sin escribir",()=>{const store=memory();assert.throws(()=>writeLibrary(store,null,[rig()],catalog,0),/Máximo/);assert.equal(store.data.size,0);});
console.log(`PLANIFICADOR: ${checks} pruebas y 300 combinaciones correctas. No sustituye ensayos físicos.`);
